### ISSUE TITLE
Option to keep items and/or experience

### ISSUE THREAD

**Issue by Fonjask** [robinjam/keep-items#3]
Is it possible to implement an option that will allow me to set it so players keep their experience when they die, but lose their items? (/keepitems exp as a toggle and /keepitems items)

**Comment by robinjam** [comment]
This is already implemented - just give players the keep-items.experience permission but not the keep-items.items permission.

More info under the **Permissions** heading on [the BukkitDev page](http://dev.bukkit.org/server-mods/keep-items/).
