### ISSUE TITLE
Players not keeping items on death

### ISSUE THREAD

**Issue by sorifiend** [robinjam/keep-items#8]
Craftbukkit: 1.4.2-R0.2 b2455
Keep Items: 1.0.rc2

Since the 1.4.2 update players loose items on death by normal cause, we have tested:
falling, spiders, command /kill, pvp, drowning

Console Message:
[KeepItems] Player sorifiend died due to an unknown cause. It is therefore impossible to determine whether or not they have permission to keep their items. Their items and experience will be dropped at their death location

I have had reports that this only happens for the first 5-10min after logging into the server, and after that the plugin appears to work correctly until the next time that player logs in.

One other thing to add, with the addition of the command block I think the death check methods have been altered, since there is one that allows OP's to set keepInventory to true with: /gamerule keepinventory true

Thanks for the great plugin.

**Comment by robinjam** [comment]
Thank you very much for the detailed bug report. I'm afraid I was unable to reproduce the bug on CraftBukkit v1.4.2-R0.2 (build 2455) and KeepItems v1.0.rc2 (I keep my items when I die and no error appears in the console). If you could provide me with some more info so I can reproduce the bug and work out what's causing it, it'd be much appreciated.

Which plugins do you have installed? (output of `plugins` command in server console)
Which version of Java do you have installed? (output of `java -version` in terminal on server)

Thanks again for the report.

**Comment by sorifiend** [comment]
Thanks for the response, and sorry for taking so long to get back to you, I missed the github email.

```
java version "1.7.0_07"
Java(TM) SE Runtime Environment (build 1.7.0_07-b11)
Java HotSpot(TM) 64-Bit Server VM (build 23.3-b01, mixed mode)
```

```
[INFO] Plugins (31):
TimTheEnchanter
ChatFilter
NoCheatPlus - 3.8.0-RC-b207
VoxelSniper - 5.168
VanishNoPacket
PermissionsBukkit
LogBlock
AntiInvisibilityPotion
EggsManager
MyHelpPages
WorldEdit - 5.4.5
WorldGuard - 5.6.5
NZnetwork
Whitelist
KeepItems - 1.0.rc2
SignColours
TeleConfirmLite
TimeShift
Warp
SkylandsPlus
SimpleChestLock
ClearLag
GriefPrevention
PetSecure
MultiHome
LagMeter
Vault
Multiverse-Core - 2.5-b628
Multiverse-Portals
Multiverse-Inventories - 2.5-b282
Multiverse-NetherPortals
```

I cant really think of what would interfere with a death event, but I have included a few plugin versions just in case.
I will run through my list, and remove plugins 1 by 1 and see if I can find a cause.

**Comment by robinjam** [comment]
Did you ever work out what was causing the problem? I still can't reproduce it (just tested it on 1.4.6-R0.1).

**Comment by Davexx** [comment]
Hi Robinjam,
I have had a similar problem on my server that I have not been able to isolate as it happens very infrequently.
3 players have complained that they have logged in and all their inventory items are missing.  One player gave me more details of his experience and it seems that just before he logged out, someone PVP-killed him.  When he logged in the next day he had none of his items.
This would make sense that dying just before logging out (and not respawning and THEN logging out) may result in a player not keeping his items.  I was wondering if it warranted looking into.  I cross-checked my list of plug-ins with Sorifiend's list and this is what we have in common:
- WorldEdit
- Keepitems v1.0 RC2
- SimpleChestLock v1.2
- Vault 

I hope this helps get to the root of the issue, if in fact it is an issue with Keepitems.

Thanks, by the way, for a great plug-in.  The players really like to keep their items and it makes the game less upsetting for younger players (and older players too!:-)
